import 'package:flutter/material.dart';

// Add this to a new file: lib/utils/app_localizations.dart
class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'KisanSahayak',
      'login': 'Login',
      'register': 'Register',
      'forgotPassword': 'Forgot Password?',
      'mobileOrEmail': 'Mobile Number / Email',
      'password': 'Password',
      'dontHaveAccount': "Don't have an account?",
      'or': 'OR',
      'chooseLanguage': 'Choose Language',
      'continue': 'Continue',
      'home': 'Home',
      'hardware': 'Hardware',
      'faq': 'FAQ',
      'myCrop': 'My Crop',
      'krishiGyan': 'Krishi Gyan',
      'changeLanguage': 'Change Language',
      'latestUpdates': 'Latest Updates',
      'title1': 'Crop Rotation Benefits',
      'title2': 'New Irrigation System',
      'title3': 'Organic Fertilizers',
      'desc1': 'Learn about sustainable farming techniques',
      'desc2': 'Save water with modern technology',
      'desc3': 'Boost yields naturally',
      'tasks': 'Today\'s Tasks',
      'item1': 'Water Wheat field',
      'item2': 'Apply Pesticides',
      'item3': 'Harvest Corn',
      'aiTitle': 'Crop Disease',
      'aiDesc': 'Analyze plant health',
      'fieldTitle': 'Field Scanning',
      'fieldDesc': 'Monitor your fields',
      'chatAITitle': 'Ask Our AI',
      'chatAIDesc': 'Get personalized farming advice',
      'shop': 'Shop',
      'q1': 'What are you looking for?',
      'option1': 'Farming Tools',
      'option2': 'Crops',
      'toolsH': 'Agricultural Tools',
      'tool1T': 'Hand Tools',
      'tool2T': 'Power Tools',
      'tool3T': 'IoT Sensors',
      'tool4T': 'Irrigation Systems',
      'tool1D': 'Basic farming tools for manual work',
      'tool2D': 'Efficient tools for faster work',
      'tool3D': 'Smart monitoring for your farm',
      'tool4D': 'Water management solutions',
      'tool1De':
          'Hand tools include shovels, hoes, pruning shears, and other manual implements essential for basic farming tasks.',
      'tool2De':
          'Power tools include tillers, chainsaws, and trimmers that increase efficiency and reduce manual labor.',
      'tool3De':
          'IoT sensors monitor soil moisture, temperature, and other important parameters to optimize crop growth.',
      'tool4De':
          'Irrigation systems include drip, sprinkler, and other water distribution technologies for efficient water usage.',
      'cropT': 'Crop Seeds',
      'crop1T': 'Wheat Seeds',
      'crop2T': 'Rice Seeds',
      'crop3T': 'Cotton Seeds',
      'crop4T': 'Soybean Seeds',
      'crop1D': 'High-yield wheat variety',
      'crop2D': 'Premium paddy seeds',
      'crop3D': 'BT cotton seeds',
      'crop4D': 'High protein variety',
      'crop1De': 'Drought-resistant wheat variety suitable for most soil types. Growing season: 100-120 days.',
      'crop2De': 'High Yielding paddy seeds suitable for wetland cultivation',
      'crop3De': 'BT Cotton with pest resistance and high yield potential',
      'crop4De': 'High protein soybean seeds with good drought tolerance.',
      'faq1':'How to use soil moisture sensors?',
      'faq2':'What crops are suitable for my region?',
      'faq3':'How to troubleshoot hardware issues?',
      'faq4':'When is the best time to harvest?',
      'faq5':'How do I update my device firmware?',
      'faq1A':'Install the sensor probe in soil at root level. Connect to the receiver and calibrate according to soil type. Monitor readings through the app.',
      'faq2A':'The app analyzes your location, soil type, and climate data to recommend suitable crops. Go to My Crop section and use the Crop Advisor feature.',
      'faq3A':'Check power supply and connections. Ensure devices are within network range. Clean sensors regularly. For persistent issues, contact customer support.',
      'faq4A':'Optimal harvest time varies by crop. The app provides notifications based on crop maturity, weather forecasts, and market conditions.',
      'faq5A':'Go to Hardware section, select your device, and check for available updates. Ensure your device is charged above 50% before updating.',
    },
    'hi': {
      'appTitle': 'किसानसहायक',
      'login': 'लॉगिन',
      'register': 'रजिस्टर',
      'forgotPassword': 'पासवर्ड भूल गए?',
      'mobileOrEmail': 'मोबाइल नंबर / ईमेल',
      'password': 'पासवर्ड',
      'dontHaveAccount': "खाता नहीं है?",
      'or': 'या',
      'chooseLanguage': 'भाषा चुनें',
      'continue': 'जारी रखें',
      'home': 'होम',
      'hardware': 'हार्डवेयर',
      'faq': 'अक्सर पूछे जाने वाले प्रश्न',
      'myCrop': 'मेरी फसल',
      'krishiGyan': 'कृषि ज्ञान',
      'changeLanguage': 'भाषा बदलें',
      'latestUpdates': 'नवीनतम अपडेट',
      'title1': 'फसल चक्र के लाभ',
      'title2': 'नई सिंचाई प्रणाली',
      'title3': 'जैविक उर्वरक',
      'desc1': 'टिकाऊ खेती की तकनीकों के बारे में जानें',
      'desc2': 'आधुनिक तकनीक से जल बचाएँ',
      'desc3': 'स्वाभाविक रूप से पैदावार बढ़ाएँ',
      'tasks': 'आज के कार्य',
      'item1': 'गेहूं के खेत में पानी दें',
      'item2': 'कीटनाशकों का प्रयोग करें',
      'item3': 'मक्के की कटाई करें',
      'aiTitle': 'फसल रोग',
      'aiDesc': 'पौधों के स्वास्थ्य का विश्लेषण करें',
      'fieldTitle': 'फ़ील्ड स्कैनिंग',
      'fieldDesc': 'अपने खेतों की निगरानी करें',
      'chatAITitle': 'हमारे एआई से पूछें',
      'chatAIDesc': 'व्यक्तिगत खेती संबंधी सलाह प्राप्त करें',
      'shop': 'दुकान',
      'q1': 'तुम क्या ढूंढ रहे हो',
      'option1': 'खेती के औज़ार',
      'option2': 'फसलें',
      'toolsH': 'कृषि उपकरण',
      'tool1T': 'हाथ के उपकरण',
      'tool2T': 'पॉवर उपकरण',
      'tool3T': 'IoT सेंसर',
      'tool4T': 'सिंचाई प्रणाली',
      'tool1D': 'मैनुअल काम के लिए बुनियादी कृषि उपकरण',
      'tool2D': 'Efficient tools for faster work',
      'tool3D': 'तेजी से काम करने के लिए कुशल उपकरण',
      'tool4D': 'जल प्रबंधन समाधान',
      'tool1De': 'हाथ के औजारों में फावड़े, कुदालें, छंटाई करने वाली कैंची और अन्य मैनुअल उपकरण शामिल हैं जो बुनियादी कृषि कार्यों के लिए आवश्यक हैं।',
      'tool2De': 'विद्युत उपकरणों में टिलर, चेनसॉ और ट्रिमर शामिल हैं जो कार्यकुशलता बढ़ाते हैं और शारीरिक श्रम को कम करते हैं।',
      'tool3De': 'फसल की वृद्धि को अनुकूलतम बनाने के लिए IoT सेंसर मिट्टी की नमी, तापमान और अन्य महत्वपूर्ण मापदंडों की निगरानी करते हैं।',
      'tool4De': 'सिंचाई प्रणालियों में जल के कुशल उपयोग के लिए ड्रिप, स्प्रिंकलर और अन्य जल वितरण प्रौद्योगिकियां शामिल हैं।',
      'cropT': 'फसल के बीज',
      'crop1T': 'गेहूं के बीज',
      'crop2T': 'चावल के बीज',
      'crop3T': 'कपास के बीज',
      'crop4T': 'सोयाबीन के बीज',
      'crop1D': 'उच्च उपज वाली गेहूं की किस्म',
      'crop2D': 'प्रीमियम धान के बीज',
      'crop3D': 'बीटी कपास के बीज',
      'crop4D': 'उच्च प्रोटीन किस्म',
      'crop1De': 'सूखा प्रतिरोधी गेहूँ की किस्म, जो अधिकांश मिट्टी के प्रकारों के लिए उपयुक्त है। उगने का समय: 100-120 दिन।',
      'crop2De': 'आर्द्रभूमि खेती के लिए उपयुक्त उच्च उपज वाले धान के बीज।',
      'crop3De': 'कीट प्रतिरोधकता और उच्च उपज क्षमता वाले बीटी कपास के बीज।',
      'crop4De': 'उच्च प्रोटीन युक्त सोयाबीन बीज, जो सूखा सहन करने में अच्छे होते हैं।',
      'faq1':'मृदा नमी सेंसर का उपयोग कैसे करें?',
      'faq2':'मेरे क्षेत्र के लिए कौन सी फसलें उपयुक्त हैं?',
      'faq3':'हार्डवेयर समस्याओं का निवारण कैसे करें?',
      'faq4':'फसल काटने का सबसे अच्छा समय क्या है?',
      'faq5':'मैं अपने डिवाइस का फ़र्मवेयर कैसे अपडेट करूं?',
      'faq1A':'सेंसर जांच को मिट्टी में जड़ स्तर पर स्थापित करें। रिसीवर से कनेक्ट करें और मिट्टी के प्रकार के अनुसार कैलिब्रेट करें। ऐप के माध्यम से रीडिंग की निगरानी करें।',
      'faq2A':'ऐप आपके स्थान, मिट्टी के प्रकार और जलवायु डेटा का विश्लेषण करके उपयुक्त फसलों की सिफारिश करता है। मेरी फसल अनुभाग पर जाएँ और फसल सलाहकार सुविधा का उपयोग करें।',
      'faq3A':'बिजली की आपूर्ति और कनेक्शन की जाँच करें। सुनिश्चित करें कि डिवाइस नेटवर्क रेंज में हैं। सेंसर को नियमित रूप से साफ करें। लगातार समस्याओं के लिए, ग्राहक सहायता से संपर्क करें।',
      'faq4A':'फसल की कटाई का इष्टतम समय हर फसल के हिसाब से अलग-अलग होता है। ऐप फसल की परिपक्वता, मौसम के पूर्वानुमान और बाज़ार की स्थितियों के आधार पर सूचनाएं प्रदान करता है।',
      'faq5A':'हार्डवेयर सेक्शन में जाकर अपना डिवाइस चुनें और उपलब्ध अपडेट की जांच करें। अपडेट करने से पहले सुनिश्चित करें कि आपका डिवाइस 50% से ज़्यादा चार्ज हो।',
    },
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations('en');
  }
}
